<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class Certificaatproduct extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		$this->hasOne("productid", "Product", "id");
                                $this->hasOne("Certificaatid", "Certificaat", "id");
                                $this->hasOne("statusid", "Status", "id");
                                
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	
	
	
							/**
							 * @Column(type="VARCHAR ( 36 )", nullable=0)
							 */	
							  public $productid;
							
							
							/**
							 * @Column(type="VARCHAR ( 36 )", nullable=0)
							 */	
							  public $certificaatid;
							
							
							/**
							 * @Column(type="VARCHAR ( 36 )", nullable=0)
							 */	
							  public $statusid;
							
							
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=1)
							 */	
							  public $titel;
							
							
							/**
							 * @Column(type="TEXT", nullable=0)
							 */	
							  public $opmerking;
							
							

	
    public function validation()
    {
	
	

        return $this->getMessages();
    }

    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("productid" => "productid","certificaatid" => "certificaatid","statusid" => "statusid","id" => "id","titel" => "titel","opmerking" => "opmerking");
    }
}