<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class Documenttemplate extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	
	
	
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=1)
							 */	
							  public $titel;
							
							
							/**
							 * @Column(type="TEXT", nullable=0)
							 */	
							  public $inhoud;
							
							

	
    public function validation()
    {
	
	

        return $this->getMessages();
    }

    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("id" => "id","titel" => "titel","inhoud" => "inhoud");
    }
}