<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class Languages extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	
	
	
							/**
							 * @Column(type="VARCHAR", length=255, nullable=0)
							 */	
							  public $eng;
							
							
							/**
							 * @Column(type="VARCHAR", length=255, nullable=1)
							 */	
							  public $nl;
							
							
							/**
							 * @Column(type="VARCHAR", length=255, nullable=1)
							 */	
							  public $de;
							
							
							/**
							 * @Column(type="VARCHAR", length=255, nullable=1)
							 */	
							  public $sp;
							
							

	
	public function validation()
    {
	
	
					
						$this->validate(new Uniqueness(
							array(
								"field"   => "eng",
								"message" => "Het veld eng moet uniek zijn."
							)
						  ));
							
				
						 
	
	}
 
    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("id" => "id","eng" => "eng","nl" => "nl","de" => "de","sp" => "sp");
    }
}