<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class MgmtEmail extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	
	/**
	 * @Column(type="VARCHAR", length=255, nullable=0)
	 */	
	  public $subject;
	
	
	/**
	 * @Column(type="TEXT", nullable=0)
	 */	
	  public $message;
	
	
	/**
	 * @Column(type="VARCHAR", length=255, nullable=0)
	 */	
	  public $from;
	
	
	/**
	 * @Column(type="VARCHAR", length=255, nullable=0)
	 */	
	  public $to;
	
	
	/**
	 * @Column(type="VARCHAR", length=11, nullable=1)
	 */	
	  public $status;
	
	
	/**
	 * @Column(type="VARCHAR", length=36, nullable=1)
	 */	
	  public $userid;
	
	
	/**
	 * @Column(type="VARCHAR", length=36, nullable=1)
	 */	
	  public $authorid;
	
	
	/**
	 * @Column(type="DATETIME", nullable=1)
	 */	
	  public $creationdate;
	
	
	/**
	 * @Column(type="DATETIME", nullable=0)
	 */	
	  public $lastedit;
	
	
	/**
	 * @Column(type="VARCHAR", length=255, nullable=1)
	 */	
	  public $source;
								
	public function validation()
    {
	
	
	
	}
 
    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("id" => "id","subject" => "subject","message" => "message","from" => "from","to" => "to","status" => "status","userid" => "userid","authorid" => "authorid","creationdate" => "creationdate","lastedit" => "lastedit","source" => "source");
    }
}