<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class MgmtModule extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	/**
	 * @Column(type="varchar", length=255, nullable=0)
	 */	
	  public $titel;
	
	
	/**
	 * @Column(type="varchar", length=255, nullable=1)
	 */	
	  public $slug;
	
	
	/**
	 * @Column(type="varchar", length=255, nullable=1)
	 */	
	  public $icon;
							
							

	
	public function validation()
    {
	
	
	
	}
 
    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("id" => "id","titel" => "titel","slug" => "slug","icon" => "icon");
    }
}