<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class Module extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	
	
	
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=1)
							 */	
							  public $titel;
							
							
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=0)
							 */	
							  public $icon;
							
							
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=1)
							 */	
							  public $slug;
							
							

	
    public function validation()
    {
	
	
					
                                            $this->validate(new Uniqueness(
                                                    array(
                                                            "field"   => "slug",
                                                            "message" => "Het veld slug moet uniek zijn."
                                                    )
                                              ));


                                             

        return $this->getMessages();
    }

    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("id" => "id","titel" => "titel","icon" => "icon","slug" => "slug");
    }
}