<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class Plane extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	
	
	
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=0)
							 */	
							  public $titel;
							
							
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=0)
							 */	
							  public $slug;
							
							
							/**
							 * @Column(type="TEXT", nullable=0)
							 */	
							  public $beschrijving;
							
							
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=0)
							 */	
							  public $staartnummer;
							
							
							/**
							 * @Column(type="VARCHAR( 36 )", length=36, nullable=0)
							 */	
							  public $fileid;
							
							
							/**
							 * @Column(type="DATE", nullable=0)
							 */	
							  public $firstflight;
							
							
							/**
							 * @Column(type="VARCHAR( 36 )", length=36, nullable=1)
							 */	
							  public $authorid;
							
							
							/**
							 * @Column(type="DATETIME", nullable=1)
							 */	
							  public $creationdate;
							
							
							/**
							 * @Column(type="VARCHAR( 36 )", length=36, nullable=1)
							 */	
							  public $userid;
							
							
							/**
							 * @Column(type="DATETIME", nullable=0)
							 */	
							  public $nextscheduledflight;
							
							

	
    public function validation()
    {
	
	
					
                                            $this->validate(new Uniqueness(
                                                    array(
                                                            "field"   => "slug",
                                                            "message" => "Het veld slug moet uniek zijn."
                                                    )
                                              ));


                                             

        return $this->getMessages();
    }

    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("id" => "id","titel" => "titel","slug" => "slug","beschrijving" => "beschrijving","staartnummer" => "staartnummer","fileid" => "fileid","firstflight" => "firstflight","authorid" => "authorid","creationdate" => "creationdate","userid" => "userid","nextscheduledflight" => "nextscheduledflight");
    }
}