<?php
use Phalcon\Mvc\Model\Validator\Uniqueness as Uniqueness;

/**
 * This is an autogenerated MGMT V0.2 MODEL 
 * DO NOT REMOVE ANNOTATIONS, YOU CANNOT CHANGE THIS ENTITY IF YOU DO!
 *
 * @AmazingClass(true)
 */
class Testentity extends \Phalcon\Mvc\Model
{
    public function initialize()
    {
		
	}
	
	public function beforeCreate()
    {
        $this->creationdate = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->lastedit = date('Y-m-d H:i:s');
    }

	/**
     * @Primary
     * @Identity
     * @Column(type="string", length=36, nullable=false)
     */
    public $id;
	
	
	
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=0)
							 */	
							  public $titel;
							
							
							/**
							 * @Column(type="VARCHAR( 36 )", length=36, nullable=1)
							 */	
							  public $authorid;
							
							
							/**
							 * @Column(type="TEXT", nullable=0)
							 */	
							  public $beschrijving;
							
							
							/**
							 * @Column(type="DATETIME", nullable=0)
							 */	
							  public $lastedit;
							
							
							/**
							 * @Column(type="INT( 11 )", length=11, nullable=1)
							 */	
							  public $testnummer;
							
							
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=0)
							 */	
							  public $slug;
							
							
							/**
							 * @Column(type="DATETIME", nullable=1)
							 */	
							  public $creationdate;
							
							
							/**
							 * @Column(type="VARCHAR( 255 )", length=255, nullable=0)
							 */	
							  public $tags;
							
							

	
    public function validation()
    {
	
	
					
                                            $this->validate(new Uniqueness(
                                                    array(
                                                            "field"   => "slug",
                                                            "message" => "Het veld slug moet uniek zijn."
                                                    )
                                              ));


                                             

        return $this->getMessages();
    }

    /**
     * Independent Column Mapping.
     */
    public function columnMap()
    {
        return array("id" => "id","titel" => "titel","authorid" => "authorid","beschrijving" => "beschrijving","lastedit" => "lastedit","testnummer" => "testnummer","slug" => "slug","creationdate" => "creationdate","tags" => "tags");
    }
}